title: Blog IA y Estudiantes
email: rmartincalderer@gmail.com
description: >- 
  Explora cómo la inteligencia artificial transforma la forma en que los estudiantes aprenden, estudian y se preparan para el futuro.
baseurl: "/blog-ia-estudiantes" # NO lo borres
url: "https://ramonmartinc.github.io"

instagram_username: ramonmartinc_
github_username: ramonmartinc

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
